# AIFX with Microsoft SQL Server
# AIFX 配合 Microsoft SQL Server

version: '3.8'

services:
  # AIFX Main Application | AIFX 主要應用程式
  aifx-web:
    build:
      context: .
      target: production
    ports:
      - "8000:8000"
    environment:
      - AIFX_ENV=production
      - SQLSERVER_HOST=sqlserver
      - SQLSERVER_DATABASE=aifx
      - SQLSERVER_USERNAME=sa
      - SQLSERVER_PASSWORD=YourStrongPassword123!
      - SQLSERVER_DRIVER=ODBC Driver 17 for SQL Server
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      sqlserver:
        condition: service_healthy
      redis:
        condition: service_started
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
      - ./models:/app/models
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Microsoft SQL Server Express (Free) | Microsoft SQL Server Express（免費）
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    hostname: sqlserver
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=YourStrongPassword123!
      - MSSQL_PID=Express  # Use Express edition (free) | 使用Express版本（免費）
    volumes:
      - sqlserver_data:/var/opt/mssql
      - ./config/sql-init:/docker-entrypoint-initdb.d
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P YourStrongPassword123! -Q 'SELECT 1'"]
      interval: 30s
      timeout: 10s
      retries: 5
    deploy:
      resources:
        limits:
          memory: 2G  # SQL Server Express limit | SQL Server Express 限制
        reservations:
          memory: 512M

  # Redis for caching | Redis 用於快取
  redis:
    image: redis:7-alpine
    hostname: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes --maxmemory 256mb
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Optional: SQL Server Management Studio (Web UI) | 可選：SQL Server 管理工具（Web UI）
  adminer:
    image: adminer:latest
    ports:
      - "8080:8080"
    environment:
      - ADMINER_DEFAULT_SERVER=sqlserver
      - ADMINER_DESIGN=lucas
    depends_on:
      - sqlserver
    restart: unless-stopped

  # Optional: Grafana for monitoring | 可選：Grafana 用於監控
  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin123
      - GF_INSTALL_PLUGINS=grafana-clock-panel,grafana-simple-json-datasource
    volumes:
      - grafana_data:/var/lib/grafana
      - ./config/grafana:/etc/grafana/provisioning
    restart: unless-stopped

volumes:
  sqlserver_data:
    driver: local
  redis_data:
    driver: local  
  grafana_data:
    driver: local

networks:
  default:
    name: aifx-network