# AIFX 數據源配置文件
# AIFX Data Sources Configuration

forex_data_sources:
  yahoo:
    enabled: true
    priority: 1
    websocket:
      url: "wss://streamer.finance.yahoo.com"
      max_reconnect_attempts: 10
      reconnect_interval: 5
      heartbeat_interval: 30
    symbols:
      USDJPY: "USDJPY=X"
    
  oanda:
    enabled: false
    priority: 2
    streaming:
      base_url: "https://stream-fxpractice.oanda.com/v3/accounts"
      account_id: "YOUR_ACCOUNT_ID"
      access_token: "YOUR_ACCESS_TOKEN"
    instruments:
      - "USD_JPY"

# 數據庫配置
database:
  host: "localhost"
  port: 5432
  database: "aifx"
  username: "aifx_user"
  password: "aifx_password"
  min_connections: 2
  max_connections: 20
  batch_size: 1000
  batch_timeout: 5.0

# 緩存配置
caching:
  redis:
    host: "localhost"
    port: 6379
    db: 1
    password: null
    max_connections: 20
    key_prefix: "forex:realtime"
    default_ttl: 300
    use_streams: true
    stream_maxlen: 10000

# 故障轉移配置
failover:
  enable_auto_failover: true
  failover_timeout: 30
  cross_validation: true
  max_price_deviation: 0.001
  priority_order:
    - "yahoo"
    - "oanda"

# 數據質量配置
data_quality:
  price_change_threshold: 0.02
  min_quality_score: 0.8
  consecutive_failures_limit: 3
  max_latency_ms: 5000
  min_data_freshness: 10
  health_check_interval: 60

# 監控配置
monitoring:
  prometheus:
    enabled: true
    port: 8002
  logging:
    level: "INFO"
    format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
