# Grafana Datasources Configuration for AIFX 24/7 Trading System
# AIFX 24/7 交易系統的 Grafana 數據源配置

apiVersion: 1

datasources:
  - name: AIFX PostgreSQL
    type: postgres
    access: proxy
    url: postgres-db:5432
    database: aifx_trading_24x7
    user: aifx
    secureJsonData:
      password: $POSTGRES_PASSWORD
    jsonData:
      sslmode: disable
      maxOpenConns: 10
      maxIdleConns: 5
      connMaxLifetime: 14400
      postgresVersion: 1500
      timescaledb: false
    isDefault: true
    editable: false

  - name: AIFX Logs
    type: loki
    access: proxy
    url: http://log-aggregator:3100
    editable: false

  - name: System Metrics
    type: prometheus
    access: proxy
    url: http://aifx-trading:8089/metrics
    editable: false
    jsonData:
      httpMethod: GET
      exemplarTraceIdDestinations:
        - name: trace_id
          datasourceUid: tempo