# Free Deployment Pipeline
# 免費部署管道

name: AIFX Free Deployment

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  # Basic tests only
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
        cache: 'pip'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r requirements-test.txt

    - name: Run tests
      env:
        AIFX_ENV: testing
        SKIP_NETWORK_TESTS: true
      run: |
        python test_phase1_complete.py
        python test_integration_phase1_phase2.py
        python test_phase3_signal_combination.py

  # Build Docker image (without push)
  build:
    name: Build Docker Image
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/main'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile
        target: production
        push: false
        tags: aifx:latest
        cache-from: type=gha
        cache-to: type=gha,mode=max

  # Deploy to Railway (example)
  deploy-railway:
    name: Deploy to Railway
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Railway CLI
      run: |
        curl -fsSL https://railway.app/install.sh | sh
        echo "$HOME/.railway/bin" >> $GITHUB_PATH

    - name: Deploy to Railway
      env:
        RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
      run: |
        railway up --detach

  # Notify deployment status
  notify:
    name: Deployment Notification
    runs-on: ubuntu-latest
    needs: [deploy-railway]
    if: always()
    
    steps:
    - name: Notify success
      if: needs.deploy-railway.result == 'success'
      run: |
        echo "✅ AIFX successfully deployed to free tier!"
        echo "🌐 Your app should be available at your Railway URL"

    - name: Notify failure
      if: needs.deploy-railway.result == 'failure'
      run: |
        echo "❌ Deployment failed - check the logs"